// demos/src/Tutorials/1-3-yjs/React/Note.tsx
import { Collaboration } from '@inkflow/extension-collaboration'
import { EditorContent, useEditor } from '@inkflow/react'
import { StarterKit } from '@inkflow/starter-kit'
import React from 'react'
import * as Y from 'yjs'

import type { TNote } from './types.js'

export default ({ note }: { note: TNote }) => {
  const doc = new Y.Doc()

  const editor = useEditor({
    content: note.defaultContent,
    editorProps: {
      attributes: {
        class: 'textarea',
      },
    },
    extensions: [
      StarterKit.configure({
        history: false, // important because history will now be handled by Y.js
      }),
      Collaboration.configure({
        document: doc,
      }),
    ],
  })

  return (
    // @ts-ignore
    <EditorContent editor={editor} />
  )
}

// demos/src/Tutorials/1-3-yjs/Vue/Note.vue
<script setup lang="ts">
import { Collaboration } from '@inkflow/extension-collaboration'
import StarterKit from '@inkflow/starter-kit'
import { EditorContent, useEditor } from '@inkflow/vue-3'
import * as Y from 'yjs'

import type { TNote } from './types.js'

const props = defineProps<{ note: TNote }>()

const doc = new Y.Doc()

const editor = useEditor({
  content: props.note.defaultContent,
  editorProps: {
    attributes: {
      class: 'textarea',
    },
  },
  extensions: [
    StarterKit.configure({
      history: false, // important because history will now be handled by Y.js
    }),
    Collaboration.configure({
      document: doc,
    }),
  ],
})
</script>

<template>
  <editor-content :editor="editor" />
</template>
