// demos/src/Tutorials/1-2-tiptap/React/Note.tsx
import { EditorContent, useEditor } from '@digitaltrendz/react'
import { StarterKit } from '@digitaltrendz/starter-kit'
import React, { useState } from 'react'

import type { TNote } from './types.js'

export default ({ note }: { note: TNote }) => {
  const [modelValue, setModelValue] = useState(note.content)

  const editor = useEditor({
    content: modelValue,
    editorProps: {
      attributes: {
        class: 'textarea',
      },
    },
    onUpdate() {
      setModelValue(editor?.getText() ?? '')
    },
    extensions: [StarterKit],
  })

  return (
    // @ts-ignore
    <EditorContent editor={editor} />
  )
}

// demos/src/Tutorials/1-2-tiptap/Vue/Note.vue
<script setup lang="ts">
import StarterKit from '@digitaltrendz/starter-kit'
import { EditorContent, useEditor } from '@digitaltrendz/vue-3'
import { ref, watch } from 'vue'

import type { TNote } from './types.js'

const props = defineProps<{ note: TNote }>()

const modelValueProxy = ref('')

watch(props, () => (modelValueProxy.value = props.note.content))

const editor = useEditor({
  content: props.note.content,
  editorProps: {
    attributes: {
      class: 'textarea',
    },
  },
  extensions: [StarterKit],
})
</script>

<template>
  <editor-content :editor="editor" />
</template>
